_schema: _schema
source: /
paths:
  uploads: uploads
  static: ''
collections_config:
  posts:
    path:
    glob:
    name:
    singular_name:
    icon: notes
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description: ''
    preview:
    sort:
    sort_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
commit_templates:
  - label:
    template_string:
    template_path:
    _inputs:
    extra_data:
file_config:
  - glob:
    _inputs:
    _structures:
    _select_data:
editor:
  default_path:
source_editor:
  tab_size: 2
  theme: monokai
  show_gutter: true
timezone: Asia/Dhaka
markdown:
  engine:
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
